version: '3'
#Define services
services:

  #Eureka Server
  eureka-server:
    image: alok001/eureka-server
    container_name: eureka-server
    ports:
      - 8761:8761 # Forward the exposed port 8761 on the container to port 8761 on the host machine
    expose:
      - 8761
  #Eureka Server
  movie-info-service:
    image: alok001/movie-info-service
    container_name: movie-info-service
    ports:
      - 8082:8082 # Forward the exposed port 8761 on the container to port 8761 on the host machine
    expose:
      - 8082
    links:
      - eureka-server
     


  